name: video_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  chewie: ^1.3.6
  video_player: ^2.4.9
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  miniplayer: ^1.0.1
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  auto_route: ^7.7.1
  flutter_hooks: ^0.18.6
  kt_dart: ^1.1.0
  injectable: ^2.1.2
  get_it: ^7.6.0
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  auto_route_generator: ^7.2.0
  injectable_generator: ^2.1.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/media.json
